name: Azure App Service CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x' # Встановлюємо версію Node.js 14.x

    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        npm test
    
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: release
      
    - name: Unzip artifact for deployment
      run: unzip release.zip

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_08504D695A5C4AE99C24EA2308A1C448 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D21A4F5F5C78437D82DAEF377017C27A }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CE62573BFE1E4D86928EE3C29A2047B7 }}

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'typing-club'
        slot-name: 'Production'
        package: .
